### ISSUE TITLE
Outdated Django Version

### ISSUE THREAD

**Issue by personjerry** [TwilioDevEd/account-security-quickstart-django#6]
Running this out of the box gives the following error (from Django code):
`SyntaxError: Generator expression must be parenthesized`

This is because the Django version used is outdated, see https://stackoverflow.com/questions/51265858/syntaxerror-generator-expression-must-be-parenthesized.

To fix this, requirements.txt needs to be updated to at least `django==1.11.17`

**Comment by spalmertwilio** [comment]
@personjerry we have updated Django to 2.2.3 and Python to 3.
